### ISSUE TITLE
似乎换了加密方式，脚本已经失效

### ISSUE THREAD

**Issue by Mosney** [minimAluminiumalism/JaponxDownloader#2]
> Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 167, in main
    URL, m3u8url, m3u8text = get_clear_m3u8file(headers, url, refererurl)
  File "main.py", line 19, in get_clear_m3u8file
    m3u8url = re.findall(patterns, clear_ajax_text)[0]
IndexError: list index out of range

**Comment by minimAluminiumalism** [comment]
我已经修复了这个问题，但是考虑到 Japonx 站长频繁地更改反爬方式，而我已没有太多的精力维护，所以无法再继续开源此脚本，不过可以向少数人开放，但是需要满足几个条件：
1.可以每天定期地下载最新的非 VIP 影片，主要是字幕片；
2.愿意定期将影片公开发布出来供他人下载（网盘、直链或 Torrent，下载方式可以协商）。
如果你认为自己满足以上条件，请使通过Telegram 联系我，我会给你最新的代码。
我希望因为开源而受益的用户自身也能有开源的精神。

**Comment by xunzh2000** [comment]
支持。我加你

**Comment by xunzh2000** [comment]
我看了您的留言，我能得到最新的代码吗？我能满足您的两个条件，谢谢。tele加您了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MosDos <notifications@github.com&gt;
发送时间: 2019年11月22日 15:09
收件人: minimAluminiumalism/JaponxDownloader <JaponxDownloader@noreply.github.com&gt;
抄送: xunzh2000 <67015683@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[minimAluminiumalism/JaponxDownloader] 似乎换了加密方式，脚本已经失效 (#2)




Closed #2.
